### ISSUE TITLE
goleak is no longer compatible with Go 1.5+

### ISSUE THREAD

**Issue by Syuparn** [uber-go/goleak#85]
[Readme](https://github.com/uber-go/goleak#installation) explains this is compatible with Go `1.5+`.
However, the latest version `v1.2.0` only works on Go `1.18+`.

Sample code:

```go
package main

import (
	"testing"

	"go.uber.org/goleak"
)

func TestLeak(t *testing.T) {
	defer goleak.VerifyNone(t)
}
```

```bash
$ go version
go version go1.13.15 linux/amd64
$ go test
# go.uber.org/goleak
/go/pkg/mod/go.uber.org/goleak@v1.2.0/options.go:115:3: undefined: isTraceStack
note: module requires Go 1.18
FAIL    example.com/foo [build failed]
```

The previous version `v1.1.12` works expectedly. This seems due to https://github.com/uber-go/goleak/pull/79.
Is current version only compatible with Go 1.18+?

**Comment by rabbbit** [comment]
We follow the Go release policy: https://go.dev/doc/devel/release#policy

> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. 

You'll need to upgrade or stick with v1.1.12 in the meantime.

I'll update the Readme.

**Comment by Syuparn** [comment]
@rabbbit 

I see. Thank you for your reply!
