### PR TITLE
Remove mentions of Go 1.5 compatibility from Readme

### LINKED ISSUE #85: goleak is no longer compatible with Go 1.5+
[Readme](https://github.com/uber-go/goleak#installation) explains this is compatible with Go `1.5+`.
However, the latest version `v1.2.0` only works on Go `1.18+`.

Sample code:

```go
package main

import (
	"testing"

	"go.uber.org/goleak"
)

func TestLeak(t *testing.T) {
	defer goleak.VerifyNone(t)
}
```

```bash
$ go version
go version go1.13.15 linux/amd64
$ go test
# go.uber.org/goleak
/go/pkg/mod/go.uber.org/goleak@v1.2.0/options.go:115:3: undefined: isTraceStack
note: module requires Go 1.18
FAIL    example.com/foo [build failed]
```

The previous version `v1.1.12` works expectedly. This seems due to https://github.com/uber-go/goleak/pull/79.
Is current version only compatible with Go 1.18+?

### PR DESCRIPTION
**Pull request by rabbbit**
Fixes #85

We're no longer compatible with pre 1.16  since #79.

I'm opting for removing the version rather than updating it to 1.18 since we already have go.mod for this. 

Adding a pointer to the Go release policy, but I also considered dropping the mentions altogether. Copied the copy from `zap`.

### CODE REVIEW

**Review by prashantv — APPROVED** [review]

**Review by sywhang — APPROVED** [review]
Thanks!
